### ISSUE TITLE
Idea: A simple login system

### ISSUE THREAD

**Issue by julywind168** [JonasGruenwald/spectator#7]
A Idel
When the app is deployed remotely, spectator should listen on 0.0.0.0 with a secret key。when first visit the web page, should input the secret key to login. 

secret is optional, but necessary in remotely mode.

when set secret, start the login and auth system.

**Comment by JonasGruenwald** [comment]
I have considered this, but I think it would add unnecessary complexity and might be misleading people into exposing the interface publicly, which I don't think is a great idea.
I would say if you want to expose the interface, put it behind a reverse proxy which handles TLS and put your authentication there, HTTP basic auth or some SSO solution, I don't think there is much benefit in adding this to the app, or is there?

**Comment by julywind168** [comment]
> SSO

When I develop a game server using Gleam, it will eventually be deployed to a cloud server. How can I safely use Spectator to monitor the server status. (I hope only I can see the dashboard) If I were to use something similar to Nginx for forwarding, I would definitely want to implement it within Spectator

**Comment by JonasGruenwald** [comment]
I would not expose a service to the public internet unless it's absolutely necessary, use a VPN or mesh VPN (I would personally use Tailscale) to access the service running on you server without exposing it, or do port forwarding via SSH.

If you must expose it to the public internet for some reason, at _least_ put HTTP basic auth in front of it, if you use nginx you could set that up with nginx.

**Comment by julywind168** [comment]
> I would not expose a service to the public internet unless it's absolutely necessary, use a VPN or mesh VPN (I would personally use Tailscale) to access the service running on your server without exposing it, or do port forwarding via SSH.
> 
> If you must expose it to the public internet for some reason, at _least_ put HTTP basic auth in front of it, if you use nginx you could set that up with nginx.

it cool！ I understand, thank you for your answer 😄

**Comment by JonasGruenwald** [comment]
Sure! I think in general that sort of token login system is not a bad idea as an additional layer of security, Livebook does something like it too – just think right now it doesn't make sense to implement, but might revisit at a later point, thank you for the suggestion :)
